---
- hosts: localhost
  remote_user: root
  vars:
    targetEnvironment: '{{ env }}'
    home: '{{ ansible_env.HOME }}'
    gitRepos: '{{ home }}/git-repos'
    nginxSites: '/etc/nginx/sites-enabled'
    nginxWWW: '/usr/share/nginx/www'
    nginxWWWLocal: '/usr/local/share/nginx/www'
    hostsFile: /etc/hosts
    environments:
      - dev
      - gang
      - demo
      - int
    projectRoots:
      webDashboard: '{{ gitRepos }}/web-dashboard'
      webAttendee: '{{ gitRepos }}/web-attendee'
      webWidgets: '{{ gitRepos }}/web-widgets'
      webOrganizer: '{{ gitRepos }}/web-organizer'
    wwwDirectories:
      - '{{ nginxWWW }}/dev'
      - '{{ nginxWWW }}/gang'
      - '{{ nginxWWW }}/demo'
      - '{{ nginxWWW }}/qa'
      - '{{ nginxWWWLocal }}/dev'
      - '{{ nginxWWWLocal }}/gang'
      - '{{ nginxWWWLocal }}/demo'
      - '{{ nginxWWWLocal }}/qa'

  tasks:
    - name: Create WWW Directories
      become: true
      file:
        path: '{{ item }}'
        state: directory
      with_items: '{{ wwwDirectories }}'

    # --------

    - name: Check for Web-Attendee
      stat:
        path: '{{ projectRoots.webAttendee }}'
      register: webAttendeeStat

    - name: Web-Attendee
      become: true
      include_role:
        name: webAttendee
      when: webAttendeeStat.stat.isdir is defined and webAttendeeStat.stat.isdir 

    # --------

    - name: Check for Web-Dashboard
      stat:
        path: '{{ projectRoots.webDashboard }}'
      register: webDashboardStat

    - name: Web-Dashboard
      become: true
      include_role:
        name: webDashboard
      when: webDashboardStat.stat.isdir is defined and webDashboardStat.stat.isdir 

    # --------

    - name: Check for Web-Widgets
      stat:
        path: '{{ projectRoots.webWidgets }}'
      register: webWidgetsStat

    - name: Web-Widgets
      become: true
      include_role:
        name: webWidgets
      when: webWidgetsStat.stat.isdir is defined and webWidgetsStat.stat.isdir 

    # --------

    - name: Check for Web-Organizer
      stat:
        path: '{{ projectRoots.webOrganizer }}'
      register: webOrganizerStat

    - name: Web-Organizer
      become: true
      include_role:
        name: webOrganizer
      when: webOrganizerStat.stat.isdir is defined and webOrganizerStat.stat.isdir 

