
- name: 'Check if {{ source }} exists'
  stat:
    path: '{{ source }}'
  register: statSource


- name: '{{ (state == "link") | ternary("Create", "Delete") }} a link {{ source }} -> {{ destination }}'
  file:
    path: '{{ destination }}'
    src: '{{ source }}'
    state: "{{ state }}"
  when:  statSource.stat.isdir is defined and statSource.stat.isdir
