
- name: '{{ (targetEnvironment == currentEnv) | ternary("Create", "Remove") }} Symlink'
  file:
    path: '{{ symlinkItem.to }}'
    src: '{{ symlinkItem.from }}'
    state: '{{ (targetEnvironment == currentEnv) | ternary("link", "absent") }}'
  with_items: '{{ symlinks }}'
  loop_control:
    loop_var: symlinkItem